[Teams]
	teams: [frodo, aragorn, global_apps, test]
[Frodo]
	key: frodo
	elements: [Lorena, Alejandro, Josué, Swapnil, SaiCharan, Paulo]
[Aragorn]
	key: aragorn
	elements: [Marcel, Tiago, Ricardo, Andreia, Ramendra, Richa, Md]
[Global Apps]
	key: global_apps
[Test]
	key: test
	elements: [Sad, Alone]

[Notes]
file_path: c:\Users\LuizGavioli\daily_notes.txt
write_mode: append